// cell_config.dart
import 'package:freezed_annotation/freezed_annotation.dart';

// Required: associates this file with the code generated by Freezed
part 'cell_config.freezed.dart';
// Optional: For JSON serialization
part 'cell_config.g.dart';

@freezed
abstract class CellConfig with _$CellConfig {
  @JsonSerializable(explicitToJson: true)
  const factory CellConfig({
    required int pulses,
    @Default(true) bool isActive,
  }) = _CellConfig;

  factory CellConfig.fromJson(Map<String, dynamic> json) =>
      _$CellConfigFromJson(json);
}
