import '../features/metronome/models/metronome_config.dart';
import '../features/metronome/models/cell_config.dart';

const List<MetronomeConfig> mockMetronomeSettingsList = [
  MetronomeConfig(
    id: null,
    title: 'Mock Config 1',
    initialBpm: 66.0,
    cellSequence: [
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 3, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: true,
    countdownDurationSeconds: 114,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 2',
    initialBpm: 96.0,
    cellSequence: [
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 2, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 121,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 3',
    initialBpm: 42.0,
    cellSequence: [
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 297,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 4',
    initialBpm: 208.0,
    cellSequence: [
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 4, isActive: false),
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: true,
    countdownDurationSeconds: 205,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 5',
    initialBpm: 232.0,
    cellSequence: [CellConfig(pulses: 4, isActive: false)],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 156,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 6',
    initialBpm: 40.0,
    cellSequence: [
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 359,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 7',
    initialBpm: 60.0,
    cellSequence: [CellConfig(pulses: 4, isActive: false)],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 550,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 8',
    initialBpm: 104.0,
    cellSequence: [
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 3, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 365,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 9',
    initialBpm: 144.0,
    cellSequence: [
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 277,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 10',
    initialBpm: 232.0,
    cellSequence: [
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 476,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 11',
    initialBpm: 108.0,
    cellSequence: [CellConfig(pulses: 2, isActive: false)],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 378,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 12',
    initialBpm: 88.0,
    cellSequence: [
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 328,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 13',
    initialBpm: 224.0,
    cellSequence: [
      CellConfig(pulses: 4, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 521,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 14',
    initialBpm: 176.0,
    cellSequence: [CellConfig(pulses: 4, isActive: false)],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 45,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 15',
    initialBpm: 152.0,
    cellSequence: [
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: true,
    countdownDurationSeconds: 427,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 16',
    initialBpm: 58.0,
    cellSequence: [
      CellConfig(pulses: 4, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 3, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 500,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 17',
    initialBpm: 54.0,
    cellSequence: [
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 3, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 176,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 18',
    initialBpm: 63.0,
    cellSequence: [
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 3, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 306,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 19',
    initialBpm: 76.0,
    cellSequence: [
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 459,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 20',
    initialBpm: 108.0,
    cellSequence: [CellConfig(pulses: 3, isActive: false)],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 367,
    markDownbeat: true,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 21',
    initialBpm: 240.0,
    cellSequence: [
      CellConfig(pulses: 4, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 41,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 22',
    initialBpm: 66.0,
    cellSequence: [
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 2, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 401,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 23',
    initialBpm: 100.0,
    cellSequence: [
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 4, isActive: false),
      CellConfig(pulses: 4, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 284,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 24',
    initialBpm: 50.0,
    cellSequence: [
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 2, isActive: false),
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 2, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: false,
    countdownDurationSeconds: 488,
    markDownbeat: false,
  ),
  MetronomeConfig(
    id: null,
    title: 'Mock Config 25',
    initialBpm: 56.0,
    cellSequence: [
      CellConfig(pulses: 3, isActive: false),
      CellConfig(pulses: 2, isActive: false),
    ],
    strongBeatVolume: 1.0,
    weakBeatVolume: 0.6,
    useCountdownTimer: true,
    countdownDurationSeconds: 196,
    markDownbeat: true,
  ),
];
